--CREATE DATABASE "{{ NAME_DB }}" WITH ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' LC_CTYPE = 'en_US.UTF-8' TABLESPACE = pg_default CONNECTION LIMIT -1 TEMPLATE template0;
CREATE USER "{{ USER_DB }}";
ALTER USER "{{ USER_DB }}" PASSWORD "{{ PASS_DB }}";
ALTER USER "{{ USER_DB }}" CREATEDB;
--GRANT ALL PRIVILEGES ON DATABASE "{{ NAME_DB }}" TO "{{ USER_DB }}";